spring:
  application.name: grpc-client
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  mvc:
    static-path-pattern: "/resources/**"

logging:
  level:
    org.springframework:
      graphql: debug
      web: debug

grpc:
  host: localhost
  port: 8079
  is-async: false
